export const Judge = 'judge'
export const Candidate = 'candidate'
export const Contest = 'contest'
export const Evaluation = 'evaluation'
export const Discipline = 'discipline'
export const Score = 'score'
export const Adjust = 'adjust'
